[package]
name = "statemap"
version = "0.1.0"
authors = ["Kody A Kantor <kody@kkantor.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
